### ISSUE TITLE
update requirements.txt

### ISSUE THREAD

**Issue by Onkel-Toni** [pascme05/PyPowerSim#1]
I get this error message when installing packages with requirements.txt file:

ERROR: Cannot install -r requirements.txt (line 1), -r requirements.txt (line 3) and numpy~=1.24.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested numpy~=1.24.2
    pandas 1.5.3 depends on numpy>=1.20.3; python_version < "3.10"
    scipy 1.7.3 depends on numpy<1.23.0 and >=1.16.5
    The user requested numpy~=1.24.2
    pandas 1.5.3 depends on numpy>=1.20.3; python_version < "3.10"
    scipy 1.7.2 depends on numpy<1.23.0 and >=1.16.5
    The user requested numpy~=1.24.2
    pandas 1.5.3 depends on numpy>=1.20.3; python_version < "3.10"
    scipy 1.7.1 depends on numpy<1.23.0 and >=1.16.5

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

**Comment by pascme05** [comment]
Fixed using recommendation 2 for stability.
