### ISSUE TITLE
Remove all cpython-38.pyc-files from repository

### ISSUE THREAD

**Issue by Onkel-Toni** [pascme05/PyPowerSim#2]
cpython-38.pyc-files are generated after checkout and hence, not necessary in the repo. Moreover, one is not able to add those files to .gitignore, since it is part of the repo.

Btw, why are the following docu-files added to .gitignore? I think it might make sense to keep those updated instead.

docu/DOC_230423_Docu_PyPowerSim.docx
docu/datasheets/Infineon-F4-75R07W1H3_B11A-DataSheet-v03_00-EN.pdf
docu/datasheets/Infineon-IAUT300N10S5N015-DS-v01_00-EN.pdf
docu/datasheets/Infineon-IKQ75N120CS6-DS-v02_02-EN.pdf
docu/datasheets/Infineon-IPW60R017C7-DS-v02_00-EN.pdf
docu/datasheets/Infineon-IPW60R045CPA-DS-v02_00-EN.pdf
docu/literature/70-41484 (1).pdf
docu/literature/Analytical_Conduction_Loss_Calculation_of_a_MOSFET_Three-Phase_Inverter_Accounting_for_the_Reverse_Conduction_and_the_Blanking_Time.pdf
docu/literature/Analytical_Switching_Loss_Modeling_Based_on_Datasheet_Parameters_for_mosfets_in_a_Half-Bridge.pdf
docu/literature/EPE_2013_0377.pdf
docu/literature/eth-30738-01.pdf
docu/literature/IGBT+Power+Losses+Calculation+using+the+Data+Sheet+Parameters.pdf
docu/literature/New_Physical_Insights_on_Power_MOSFET_Switching_Losses.pdf
docu/literature/PED4_1042_Report.pdf

**Comment by pascme05** [comment]
Cython files are removed. Articles are not included due to copyright issues but will be added to a reference list.
